<a href="https://colab.research.google.com/github/HromovAndrey/II_mood_2_laba/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22Laba2_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
print(b.shape)

(2, 2)


In [ ]:
c = np.ones((2,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
p = np.random.random((3,2))
print(p)

[[0.83602542 0.10301411]
 [0.16993532 0.22796589]
 [0.15140417 0.71521318]]


In [ ]:
v = np.full((2,2),7)
print(v)

[[7 7]
 [7 7]]


In [ ]:
z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


In [ ]:
x = np.arange(10,50,5)
print(x)

[10 15 20 25 30 35 40 45]


In [ ]:
m = np.arange(1,25,3)
print(m)

[ 1  4  7 10 13 16 19 22]


In [ ]:
a = np.linspace(0., 6., num=8)
print(a)

[0.         0.85714286 1.71428571 2.57142857 3.42857143 4.28571429
 5.14285714 6.        ]


In [ ]:
s = np.array([3,4,5])
d = np.array([6,7,8])
print(f"{s=}\n")
print(f"{d=}\n")
np.vstack((s,d))

s=array([3, 4, 5])

d=array([6, 7, 8])



array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
s = np.array([[3], [5], [8]])
d = np.array([[2], [4], [6]])

print(f"{s=}\n")
print(f"{d=}\n")
np.hstack((s,d))

s=array([[3],
       [5],
       [8]])

d=array([[2],
       [4],
       [6]])



array([[3, 2],
       [5, 4],
       [8, 6]])

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(a)
print(a[0:2,1:3])
print(a[0:3, 0])
d = a[0:2, 1:3]
print(d)
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[1 5 9]
[[2 3]
 [6 7]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)
